server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8762/eureka/"
  instance:
    prefer-ip-address: true

spring:
  threads:
    virtual:
      enabled: true

  liquibase:
    change-log: database/changelog-master.xml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    jdbc-url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver