services:

  postgres:
    container_name: 'postgres'
    image: postgres:16
    restart: no
    ports:
      - '5432:5432'
    env_file:
      - 'env-db.txt'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB"]
    volumes:
      - postgres:/home/booking_animal_spa/postgres:/

  config-server:
     container_name: 'config-server'
     image: config-server
     restart: no
     ports:
       - '8888:8888'
     healthcheck:
       test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
     volumes:
       - config-server:/home/booking_animal_spa/config-server:/

  gateway:
    container_name: gateway
    image: gateway
    restart: no
    ports:
      - '80:80'
    depends_on:
      config-server:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    volumes:
      - gateway:/home/booking_animal_spa/gateway:/

  service-discovery:
    container_name: service-discovery
    image: service-discovery
    restart: on-failure
    ports:
      - '8762:8762'
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8762/actuator/health || exit 1"]
    volumes:
      - service-discovery:/home/booking_animal_spa/service-discovery:/

  user-service:
    container_name: user-service
    image: user-service
    restart: no
    ports:
      - '8080'
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    env_file:
      - 'env-conf.txt'
    volumes:
      - user-service:/home/booking_animal_spa/user-service:/

volumes:
  postgres:
  config-server:
  gateway:
  service-discovery:
  user-service:
