services:

  postgres:
    container_name: 'postgres'
    image: postgres:16
    restart: no
    ports:
      - '5432:5432'
    env_file:
      - 'env-db.txt'
    healthcheck:
      test: ["CMD_SHELL", "pg_isready -d ${DB_NAME}"]

  config-server:
     container_name: 'config-server'
     image: config-server
     restart: no
     ports:
       - '8888:8888'
     healthcheck:
       test: ["CMD-SHELL", "curl -f http://localhost:"]

  gateway:
    container_name: gateway
    image: gateway
    restart: no
    ports:
      - '80:80'
    depends_on:
      config-server:
        condition: service_healthy
      service-discovery:
        condition: service_healthy

  service-discovery:
    container_name: service-discovery
    image: service-discovery
    restart: on-failure
    ports:
      - '8762:8762'
    depends_on:
      config-server:
        condition: service_healthy

  user-service:
    container_name: user-service
    image: user-service
    restart: no
    ports:
      - '8500:8080'
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    env_file:
      - 'env-conf.txt'