services:

  postgres:
    container_name: 'postgres'
    image: postgres:16
    restart: no
    env_file:
      - 'env-db.env'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB"]
    volumes:
      - /home/booking_animal_spa/postgres:/var/lib/postgresql/data
    network_mode: host

  config-server:
     container_name: 'config-server'
     image: config-server:latest
     restart: no
     healthcheck:
       test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
     volumes:
       - /home/booking_animal_spa/config-server:./
     network_mode: host

  gateway:
    container_name: gateway
    image: gateway:latest
    restart: no
    depends_on:
      config-server:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    network_mode: host

  service-discovery:
    container_name: service-discovery
    image: service-discovery:latest
    restart: on-failure
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8762/actuator/health || exit 1"]
    network_mode: host

  user-service:
    container_name: user-service
    image: user-service:latest
    restart: no
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    env_file:
      - 'env-conf.env'
    network_mode: host