spring:
  application:
    name: gateway
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
      profile: ${spring.profiles.active}
  threads:
    virtual:
      enabled: true