spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: 'classpath:/configuration/{application}/{profile}'
  threads:
    virtual:
      enabled: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: "http://service-discovery:8762/eureka/"