spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: 'classpath:/configuration/{application}/{profile}'
server:
  port: 8888