spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: 'file:${user.dir}${file.separator}resources${file.separator}configuration${file.separator}{application}${file.separator}{profile},
          file:${user.dir}${file.separator}ConfigServer${file.separator}src${file.separator}main${file.separator}resources${file.separator}configuration${file.separator}{application}${file.separator}{profile}'
  threads:
    virtual:
      enabled: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8762/eureka/"
  instance:
    prefer-ip-address: true