server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: "http://${TEST_IP}:8762/eureka/"
  instance:
    prefer-ip-address: true

spring:
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

rsa:
  private-key: file:${user.dir}${file.separator}Gateway${file.separator}src${file.separator}main${file.separator}resources${file.separator}certs${file.separator}private.pem
  public-key: file:${user.dir}${file.separator}Gateway${file.separator}src${file.separator}main${file.separator}resources${file.separator}certs${file.separator}public.pem