server:
  port: 80
  address: ${TEST_IP}

eureka:
  client:
    service-url:
      defaultZone: "http://192.168.8.61:8762/eureka/"

spring:
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true