server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: "http://service-discovery:8762/eureka/"

spring:
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true